# Generated by Django 4.1 on 2022-08-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shreddersapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tricks',
            new_name='Trick',
        ),
    ]
